name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit safety pytest
        
    - name: Run Bandit security checks
      run: bandit -r . -f json -o bandit-results.json
      
    - name: Check dependencies for vulnerabilities
      run: safety check
      
    - name: Run tests
      run: pytest tests/ 